import Head from "next/head";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import { WalletMultiButton } from '@solana/wallet-adapter-react-ui'

export default function Home() {
  return (
    <div>
      <Head>
        <title>StreaX | Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="main bg-[#242424] w-[100vw] h-[93.6vh] flex flex-col justify-center self-center img1 ">
        <div className=" text-white font-bold text-[150px] pl-[342px] pb-[173px]">
          Strea
          <span className="text-[#D8FF69]">X</span>
          -Hub
        </div>
        <br />
        <div>
          <h2 className=" text-gray-400 text-3xl mt-[-47px] font-semibold text-center absolute top-[480px] left-[480px]">
            Community Managment at your fingertips.
          </h2>
        </div>
        <div className=" rounded-lg  absolute top-[500px] left-[700px]  bg-[#D8FF69]"> 
<WalletMultiButton/>
        </div>
      </div>
    </div>
  );
}
